export const RESUMO_COLS = [
  { label: 'Trabalhador',              key: 'nome',           align: 'left',   w: 150, group: 'id'                                                  },
  { label: 'NIF',                      key: 'nif',            align: 'center', w: 85,  group: 'id'                                                  },
  { label: 'NIS',                      key: 'nis',            align: 'center', w: 85,  group: 'id'                                                  },
  { label: 'Profissão',                key: 'profissao',      align: 'left',   w: 100, group: 'id'                                                  },
  { label: 'Empresa',                  key: 'empresa',        align: 'left',   w: 130, group: 'id'                                                  },
  { label: 'Início Vínculo',           key: 'inicioVinculo',  align: 'center', w: 88,  group: 'id'                                                  },
  { label: 'Cessação Vínculo',         key: 'cessacaoVinculo',align: 'center', w: 88,  group: 'id'                                                  },
  { label: 'Tabela IRS',               key: 'tabelaNome',     align: 'center', w: 82,  group: 'tabela'                                              },
  { label: 'Nº Dep.',                  key: 'nDep',           align: 'center', w: 54,  group: 'tabela'                                              },
  { label: 'Venc. Base (€)',           key: 'vencBase',       align: 'right',  w: 84,  group: 'venc',   sumKey: '_vencNum'                         },
  { label: 'Sub. Alim. Dias',          key: 'subsAlimDias',   align: 'center', w: 64,  group: 'venc'                                                },
  { label: 'Sub. Alim. €/dia',         key: 'subsAlimDia',    align: 'right',  w: 76,  group: 'venc'                                                },
  { label: 'Sub. Alim. Total (€)',     key: 'subsAlimTotal',  align: 'right',  w: 84,  group: 'venc',   sumKey: '_subsAlimNum'                     },
  { label: 'Sub. Férias / Duod. (€)', key: 'subsFerias',     align: 'right',  w: 84,  group: 'venc',   sumKey: '_feriasNum'                       },
  { label: 'Sub. Natal / Duod. (€)',  key: 'subsNatal',      align: 'right',  w: 84,  group: 'venc',   sumKey: '_natalNum'                        },
  { label: 'Ajudas Custo Inter. (€)', key: 'ajudas',         align: 'right',  w: 84,  group: 'venc',   sumKey: '_ajudasNum'                       },
  { label: 'Base IRS (€)',             key: 'baseIRS',        align: 'right',  w: 76,  group: 'fiscal'                                              },
  { label: 'Taxa IRS',                 key: 'taxaIRS',        align: 'right',  w: 64,  group: 'fiscal'                                              },
  { label: 'IRS (€)',                  key: 'irsTotal',       align: 'right',  w: 70,  group: 'fiscal', sumKey: '_irsNum'                          },
  { label: 'SS Trab. 11% (€)',         key: 'ssTrab',         align: 'right',  w: 80,  group: 'fiscal', sumKey: '_ssTrabNum'                       },
  { label: 'Total Abonos (€)',         key: 'totalAbonos',    align: 'right',  w: 84,  group: 'totais', sumKey: '_abonosNum',  highlight: 'blue'   },
  { label: 'Total Descontos (€)',      key: 'totalDesc',      align: 'right',  w: 84,  group: 'totais', sumKey: '_descNum'                         },
  { label: 'Líquido (€)',              key: 'liquido',        align: 'right',  w: 76,  group: 'totais', sumKey: '_liquidoNum', highlight: 'green'  },
  { label: 'TSU Patronal 23,75% (€)', key: 'ssPatronal',     align: 'right',  w: 84,  group: 'totais', sumKey: '_ssPatNum'                        },
  { label: 'Custo Empresa (€)',        key: 'custoEmpresa',   align: 'right',  w: 84,  group: 'totais', sumKey: '_custoNum',   highlight: 'rose'   },
  { label: 'Ajuste (€)',               key: 'ajuste',         align: 'right',  w: 74,  group: 'totais', sumKey: '_ajusteNum',  tipo: 'ajuste'      },
  { label: 'Ordenado Bruto (€)',       key: 'brutoAlvo',      align: 'right',  w: 96,  group: 'totais', sumKey: '_brutoNum',   highlight: 'emerald'},
  { label: 'Observação',               key: 'observacao',     align: 'center', w: 150, group: 'obs',    editable: true                             },
  { label: 'Completo',                 key: 'completo',       align: 'center', w: 64,  group: 'obs',    tipo: 'toggle'                             },
];

export const GROUP_DEFS = {
  id:     { label: 'Identificação', bg: '#334155', text: '#94a3b8', border: null      },
  tabela: { label: 'Tabela Fiscal', bg: '#4c1d95', text: '#ddd6fe', border: '#7c3aed' },
  venc:   { label: 'Vencimentos',   bg: '#1e3a8a', text: '#bfdbfe', border: '#3b82f6' },
  fiscal: { label: 'Fiscal',        bg: '#78350f', text: '#fde68a', border: '#f59e0b' },
  totais: { label: 'Totais',        bg: '#1e1b4b', text: '#c7d2fe', border: '#6366f1' },
  obs:    { label: 'Gestão',        bg: '#334155', text: '#94a3b8', border: null      },
};
